services:
  auth:
    build: ./docker
    labels:
      - "traefik.http.routers.auth-pathprefix.rule=Host(`${SERVICE_FQDN_AUTH}`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-pathprefix.priority=1000"
      - "traefik.http.routers.auth-pathprefix.entryPoints=https"
      - "traefik.http.routers.auth-pathprefix.tls=true"
      - "traefik.http.routers.auth-pathprefix.tls.certresolver=letsencrypt"
      - "traefik.http.routers.auth-pathprefix.service=auth-svc"
      - "traefik.http.services.auth-svc.loadbalancer.server.port=3000"

  app:
    build: ./example-app
    expose:
      - "3000"
    labels:
      - "traefik.http.middlewares.pb-auth.forwardauth.address=http://auth:3000/auth/verify"
      - "traefik.http.middlewares.pb-auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-Email"
