services:
  traefik:
    image: traefik:v3.6.7
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  auth:
    build: ./docker
    environment:
      - POCKETBASE_URL=https://api.levinkeller.de
      - POCKETBASE_GROUP=example
      - ADMIN_EMAIL=post@levinkeller.de
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`app.localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.priority=100"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.pb-auth.forwardauth.address=http://auth:3000/auth/verify"
      - "traefik.http.middlewares.pb-auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-Email"

  app:
    build: ./example-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.middlewares=pb-auth@docker"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
