services:
  auth:
    build: ./docker
    labels:
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID}-auth.rule=Host(`${SERVICE_FQDN_AUTH}`) && PathPrefix(`/auth`)"

  app:
    build: ./example-app
    expose:
      - "3000"
    labels:
      - "traefik.http.middlewares.pb-auth.forwardauth.address=http://auth:3000/auth/verify"
      - "traefik.http.middlewares.pb-auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-Email"
